config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :backoffice do
    resources :shows
  end
  root 'shows#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :backoffice do
    get 'backoffice' => :show
  end

  resources :shows
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/views/partials/_footer.html.erb
<footer>
  <section>
    <% if @current_user.nil? %>
      <p class="center">
        Du er ikke logget inn
      </p>
      <p class="center">
        <%= link_to "Logg inn", login_url %>
      </p>
    <% else %>
      <p class="center">
        Du er logget inn som <strong><%= @current_user.username %></strong>
      </p>
      <p class="center">
        <%= link_to "Gå til admin-portal", backoffice_url %>
      </p>
      <p class="center">
        <%= link_to "Logg ut", logout_url, data: { turbo_method: :delete} %>
      </p>
    <% end %>
  </section>
</footer>

app/views/partials/_navbar.html.erb
<nav>
  <ul>
    <li><strong><%= link_to "Jaha Produksjoner", :shows, class: "link-style-none" %></strong></li>
  </ul>
  <ul>
    <li><%= link_to "Medlemmer", :users %></li>
    <li><%= link_to "Programmer", :shows %></li>
  </ul>
</nav>