config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :backoffice do
    resources :shows
  end
  root 'shows#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :backoffice do
    get 'backoffice' => :show
  end

  resources :shows
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  admin           :boolean          default(FALSE), not null
#  email           :string           not null
#  name            :string
#  password_digest :string           default(""), not null
#  username        :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_username  (username) UNIQUE
#
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :admin, inclusion: { in: [true, false] }

  has_many :user_shows, dependent: :destroy
  has_many :shows, through: :user_shows

  def admin?
    admin
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize_user

  def index
    @users = policy_scope(User)
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    unless @user.save
      render :new, status: :unprocessable_entity
      return
    end

    session[:user_id] = @user.id
    redirect_to user_url(@user), notice: 'User was successfully created.'
  end

  def update
    unless @user.update(user_params)
      render :edit, status: :unprocessable_entity
      return
    end

    redirect_to user_url(@user), notice: 'User was successfully updated.'
  end

  def destroy
    @user.destroy!

    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :name, :password, :password_confirmation)
  end

  def authorize_user
    authorize @user || User
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_shows.html.erb
<section>
  <h2>Med i følgende programmer</h2>
  <p>
    <% if @user.shows.count == 0 %>
      <%= "det er ingen her" %>
    <% end %>
  </p>
  <% @user.shows.each do |show| %>
    <%= render show %>
  <% end %>
</section>

app/views/users/_user.html.erb
<aside id="<%= dom_id user %>">
  <%= image_tag "https://joesch.moe/api/v1/#{user.id}" %>
  <h3><%= link_to user.name || user.username, user %></h3>
</aside>

app/views/users/edit.html.erb
<header>
  <h1>Editing user</h1>
  <section>
    <%= render "form", user: @user %>
  </section>
  <div>
    <%= link_to "Show this user", @user %> |
    <%= link_to "Back to users", users_path %>
  </div>
  <% if policy(@user).destroy? %>
    <%= link_to "Slett denne brukeren", user_path(@user), data: {
      turbo_method: :delete
    }, style: "color: red;" %>
  <% end %>
</header>

app/views/users/index.html.erb
<header>
  <h1>Jahanianerne</h1>
  <p style="color: green"><%= notice %></p>
  <section>
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </section>
</header>

app/views/users/new.html.erb
<header>
  <h1>New user</h1>
  <section>
    <%= render "form", user: @user %>
  </section>
  <div>
    <%= link_to "Back to users", users_path %>
  </div>
</header>

app/views/users/show.html.erb
<header>
  <p style="color: green"><%= notice %></p>
  <h1>
    <%= @user.name %>
    <% if @user.admin? %>
      <sup>Admin</sup>
    <% end %>
  </h1>
  <p>
    Kontakt: <%= @user.email %>
  </p>
  <figure>
    <%= image_tag "https://joesch.moe/api/v1/#{@user.id}", height: 500 %>
  </figure>
  <% if policy(@user).edit? %>
    <%= link_to "Rediger bruker", edit_user_path(@user) %>
  <% end %>
  <%= render "shows" %>
</header>