config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :backoffice do
    resources :shows
  end
  root 'shows#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :backoffice do
    get 'backoffice' => :show
  end

  resources :shows
  resources :users

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/show.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: shows
#
#  id          :integer          not null, primary key
#  description :text
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_shows_on_name  (name) UNIQUE
#
class Show < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :user_shows, dependent: :destroy
  has_many :users, through: :user_shows

  def add_host(user_id)
    user = User.find_by(id: user_id)

    if user
      users << user
      return true
    end

    false
  end
end

app/controllers/backoffice/shows_controller.rb
# frozen_string_literal: true

module Backoffice
  class ShowsController < Backoffice::BaseController
    before_action :set_show, only: %i[show edit update destroy]
    before_action :authorize_user

    def index
      @shows = policy_scope(Show)
    end

    def show; end

    def new
      @show = Show.new
    end

    def edit; end

    def create
      @show = Show.new(show_params)

      if @show.save
        redirect_to backoffice_show_url(@show), notice: 'Show was successfully created.'
        return
      end

      render :new, status: :unprocessable_entity
    end

    def update
      if @show.update(show_params.except(:new_host_user_id))
        handle_new_host
        redirect_to backoffice_show_url(@show), notice: 'Show was successfully updated.'

        return
      end

      render :edit, status: :unprocessable_entity
    end

    def destroy
      @show.destroy!

      redirect_to backoffice_shows_url, notice: 'Show was successfully destroyed.'
    end

    private

    def set_show
      @show = Show.find(params[:id])
    end

    def show_params
      params.require(:show).permit(:name, :description, :new_host_user_id)
    end

    def authorize_user
      authorize @show || Show
    end

    def handle_new_host
      return if show_params[:new_host_user_id].blank?
      return if @show.add_host(show_params[:new_host_user_id])

      flash.now[:alert] = "Could not find user with ID #{show_params[:new_host_user_id]}."
    end
  end
end

app/controllers/shows_controller.rb
# frozen_string_literal: true

class ShowsController < ApplicationController
  before_action :set_show, only: %i[show edit update destroy]
  before_action :authorize_user

  def index
    @shows = policy_scope(Show)
  end

  def show; end

  def new
    @show = Show.new
  end

  def edit; end

  def create
    @show = Show.new(show_params)

    if @show.save
      redirect_to show_url(@show), notice: 'Show was successfully created.'
      return
    end

    render :new, status: :unprocessable_entity
  end

  def update
    if @show.update(show_params.except(:new_host_user_id))
      handle_new_host
      redirect_to show_url(@show), notice: 'Show was successfully updated.'

      return
    end

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @show.destroy!

    redirect_to shows_url, notice: 'Show was successfully destroyed.'
  end

  private

  def handle_new_host
    return if show_params[:new_host_user_id].blank?
    return if @show.add_host(show_params[:new_host_user_id])

    flash.now[:alert] = "Could not find user with ID #{show_params[:new_host_user_id]}."
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_show
    @show = Show.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def show_params
    params.require(:show).permit(:name, :description, :new_host_user_id)
  end

  def authorize_user
    authorize @show || Show
  end
end

app/helpers/backoffice/shows_helper.rb
# frozen_string_literal: true

module Backoffice
  module ShowsHelper
  end
end

app/helpers/shows_helper.rb
# frozen_string_literal: true

module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>
      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label "New show host (user ID)", style: "display: block" %>
    <%= form.text_field :new_host_user_id %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/_members.html.erb
<section>
  <h2>Programmets medlemmer</h2>
  <p>
    <% if @show.users.count == 0 %>
      <%= "det er ingen her" %>
    <% end %>
  </p>
  <% @show.users.each do |user| %>
    <%= render user %>
  <% end %>
</section>

app/views/shows/_show.html.erb
<aside id="<%= dom_id show %>">
  <%= image_tag "temp.svg", height: 150 %>
  <h3><%= link_to show.name, show %></h3>
  <p>
    <%= show.description %>
  </p>
</aside>

app/views/shows/edit.html.erb
<header>
  <h1>Editing show</h1>
  <div>
    <%= link_to "Show this show", @show %> |
    <%= link_to "Back to shows", shows_path %>
  </div>
  <section>
    <%= render "form", show: @show %>
  </section>
  <hr/>
  <%= render "members" %>
</header>

app/views/shows/index.html.erb
<header>
  <h1>Jaha? En hel haug med podkaster.</h1>
  <p>
    Velkommen til Jaha Produksjoner. Et Oslo-basert podkastkollektiv som lager innhold for deg som liker å ha noe på øret.
  </p>
  <p style="color: green"><%= notice %></p>
</header>
<section>
  <% @shows.each do |show| %>
    <%= render show %>
  <% end %>
</section>

app/views/shows/new.html.erb
<header>  
  <h1>New show</h1>
  <section>
    <%= render "form", show: @show %>
  </section>
  <div>
    <%= link_to "Back to shows", shows_path %>
  </div>
</header>

app/views/shows/show.html.erb
<header>
  <h1><%= @show.name %></h1>
  <p>
    <%= @show.description %>
  </p>
  <p style="color: green"><%= notice %></p>
  <% if policy(@show).edit? %>
    <p>
      <%= link_to "Edit this show", edit_show_path(@show) %>
    </p>
  <% end %>
  <p>
    <%= link_to "Back to shows", shows_path %>
  </p>
  <%= render "members" %>
</header>